#!/bin/bash

function php_context {
  /usr/bin/scl enable php54 "$1" ;
}

function update_configuration {
   # SCL bin_dir
   path=$(path_append $path $(dirname $(scl enable php54 "which php") | tr -d '\n'))

   local man_path=$(MANPATH="" scl enable php54 "printenv MANPATH")
   path_append ${MANPATH:-:} ${man_path:-:} > ${OPENSHIFT_PHP_DIR}env/MANPATH
   echo $path > ${OPENSHIFT_PHP_DIR}env/OPENSHIFT_PHP_PATH_ELEMENT
}
